events {}

http {
  upstream backend {
    # Round Robin es el default en Nginx
    server server1:80;
    server server2:80;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend;
    }
  }
}
